---

- name: Install dependencies
  ansible.builtin.apt:
    name: moreutils
  become: true

- name: Deploy Scripts for MySQL
  ansible.builtin.include_tasks: 'mysql-dump.yml'

- name: Deploy Scripts for MySQL Postgres
  ansible.builtin.include_tasks: 'postgres-dump.yml'

- name: Deploy Scripts for MySQL Zabbix
  ansible.builtin.include_tasks: 'zabbix-mysql-dump.yml'
